
--drop schema if exists Reimbursement cascade;

--create schema reimbursement;
set schema 'reimbursement';



create table "ERS_REIMBURSEMENT" (

    "REIMB_ID" numeric(10) PRIMARY KEY,
    "REIMB_AMOUNT" numeric(10) NOT NULL,
    "REIMB_SUBMITTED" timestamp(9),
    "REIMB_RESOLVED" timestamp(9),
    "REIMB_DESCRIPTION" varchar(250) NOT NULL,
    "REIMB_AUTHOR" numeric(10),
    "REIMB_RESOLVER" numeric(10),
    "REIMB_STATUS_ID" numeric(10) NOT NULL,
    "REIMB_TYPE_ID" numeric(10) NOT NULL,
    
    FOREIGN KEY ("REIMB_AUTHOR") REFERENCES "ERS_USERS"("ERS_USERS_ID"),
    FOREIGN KEY ("REIMB_RESOLVER") REFERENCES "ERS_USERS"("ERS_USERS_ID"),
    FOREIGN KEY ("REIMB_STATUS_ID") REFERENCES "ERS_REIMBURSEMENT_STATUS"("REIMB_STATUS_ID"),
    FOREIGN KEY ("REIMB_TYPE_ID") REFERENCES "ERS_REIMBURSEMENT_TYPE"("REIMB_TYPE_ID")
    
    
);

CREATE TABLE "ERS_USERS" (

    "ERS_USERS_ID" numeric(10) PRIMARY KEY,
    "ERS_USERNAME" VARCHAR(50) UNIQUE NOT NULL,
   "ERS_PASSWORD" VARCHAR(50) NOT NULL,
    "USER_FIRST_NAME" VARCHAR(100) NOT NULL,
    "USER_LAST_NAME" VARCHAR(100) NOT NULL,
    "USER_EMAIL" VARCHAR(150) UNIQUE NOT NULL,
    "USER_ROLE_ID" numeric(10) NOT NULL,
    
    FOREIGN KEY ("USER_ROLE_ID") REFERENCES "ERS_USER_ROLES"("ERS_USER_ROLE_ID")

);


CREATE TABLE "ERS_REIMBURSEMENT_STATUS" (

    "REIMB_STATUS_ID" numeric(10) PRIMARY KEY,
    "REIMB_STATUS" VARCHAR(10) NOT NULL

);


CREATE TABLE "ERS_REIMBURSEMENT_TYPE" (

    "REIMB_TYPE_ID" numeric(10) PRIMARY KEY,
    "REIMB_TYPE" VARCHAR(10) NOT NULL

);


CREATE TABLE "ERS_USER_ROLES" (

    "ERS_USER_ROLE_ID" numeric(10) PRIMARY KEY,
    "USER_ROLE" VARCHAR(10) NOT NULL

);









